id = "lotus-theme"
name = "Lotus Theme"
version = "0.1.0"
schema_version = 1
authors = ["SkyLissh <alisson.hdz.lopez@hotmail.com>"]
description = "🌸 A minimal zen theme for Zed"
repository = "https://github.com/skylissh/lotus-theme-zed"
